name: Tests

on:
  push:
    branches:
      - main  # Trigger on push to the main branch
  pull_request:
    branches:
      - main  # Trigger on pull requests to the main branch
    types:
      - opened
      - ready_for_review
      - reopened
      - synchronize

jobs:
  test_package:
    name: Tests
    runs-on: ubuntu-latest  # Use the latest Ubuntu runner

    steps:
      - uses: actions/checkout@v4  # Checkout the repository

      # Set up Python environment for Backend
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"  # Set Python version

      - name: Install Backend Dependencies
        run: |
          python -m pip install -r requirements.txt
          python -m pip install coverage pytest-cov
          python -m pip install azure-keyvault-secrets

      - name: Run Backend Tests with Coverage
        run: |
          python -m pytest -vv --cov=. --cov-report=xml --cov-report=html --cov-report=term-missing --cov-fail-under=80 --junitxml=coverage-junit.xml

      - uses: actions/upload-artifact@v4
        with:
          name: backend-coverage
          path: |
            coverage.xml  # Correct path to backend coverage
            coverage-junit.xml  # Correct path to backend JUnit report
            htmlcov/  # Correct path to backend HTML coverage report

      # Set up Node.js environment for Frontend
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20'  # Set the Node.js version

      - name: Install Frontend Dependencies
        run: |
          npm install

      - name: Run Frontend Tests with Coverage
        run: |
          npm run test -- --coverage

      - uses: actions/upload-artifact@v4
        with:
          name: frontend-coverage
          path: |
            coverage/  # Correct path to frontend coverage
            coverage/lcov-report/  # Correct path to frontend lcov report